/*
 *
 * MyPosts constants
 *
 */

const SWITCH_VIEW = 'app/MyPosts/SWITCH_VIEW',
      SET_PARTICIPANT_LIST = 'app/MyPosts/SET_PARTICIPANT_LIST',
      SET_FILTER = 'app/MyPosts/SET_FILTER',
      LOAD_POSTS = 'app/MyPosts/LOAD_POSTS',
      LOAD_POSTS_SUCCESS = 'app/MyPosts/LOAD_POSTS_SUCCESS',
      LOAD_POSTS_ERROR = 'app/MyPosts/LOAD_POSTS_ERROR';


export {
  SWITCH_VIEW,
  SET_PARTICIPANT_LIST,
  SET_FILTER,
  LOAD_POSTS,
  LOAD_POSTS_SUCCESS,
  LOAD_POSTS_ERROR
};
